// File generated by FlutterFire CLI.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;

      case TargetPlatform.windows:
        return windows;

      case TargetPlatform.linux:
        return linux;

      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );

      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );

      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZlcVsGEdrfFJejsBDhH85bbXZVmWMMuo',
    appId: '1:472786388681:web:ac2d8d0593380353b26f18',
    messagingSenderId: '472786388681',
    projectId: 'projetos-iff',
    authDomain: 'projetos-iff.firebaseapp.com',
    storageBucket: 'projetos-iff.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRF2wORYngda9ah3mS4afSogkprmBM2cU',
    appId: '1:472786388681:android:6fe1e589db116a4db26f18',
    messagingSenderId: '472786388681',
    projectId: 'projetos-iff',
    storageBucket: 'projetos-iff.firebasestorage.app',
  );
  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: "AIzaSyAbtaq_Dnlys_CY7Kfm4fkWyypTk3QTjwE",
  authDomain: "pdm-lira.firebaseapp.com",
  projectId: "pdm-lira",
  storageBucket: "pdm-lira.firebasestorage.app",
  messagingSenderId: "83494463832",
  appId: "1:83494463832:web:7a35a3092505879d3edd2d"
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZlcVsGEdrfFJejsBDhH85bbXZVmWMMuo',
    appId: '1:472786388681:web:7210d99544f5c608b26f18',
    messagingSenderId: '472786388681',
    projectId: 'projetos-iff',
    authDomain: 'projetos-iff.firebaseapp.com',
    storageBucket: 'projetos-iff.firebasestorage.app',
  );
}
